---
title: "Data Wrangling"
author: "Sophia Lecuona"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(here)
library(broom)
library(janitor)
```

# Dungeness Crab survey data

```{r}
dung_survey <- read_csv(here("data/dungeness_survey_data.csv")) 

dung_clean <- dung_survey %>%
  clean_names() %>%
  mutate(haul_id = dataset_west_coast_annual,
         stratum = x2,
         lat = x3,
         long = x4,
         depth = x5,
         year = x6,
         wtcpue = x7) %>%
  mutate(species = "dungeness") %>%
  select(species, haul_id, stratum, lat, long, depth, year, wtcpue) %>%
  drop_na()
```

# Squid survey data

```{r}
squid_survey <- read_csv(here("data/squid_survey_data.csv")) 

squid_clean <- squid_survey %>%
  clean_names() %>%
  mutate(haul_id = dataset_west_coast_annual,
         stratum = x2,
         lat = x3,
         long = x4,
         depth = x5,
         year = x6,
         wtcpue = x7) %>%
  mutate(species = "squid") %>%
  select(species, haul_id, stratum, lat, long, depth, year, wtcpue) %>%
  drop_na()
```

# Full join crab and squid

```{r}
full_dung_squid <- full_join(
  dung_clean,
  squid_clean,
  by = NULL,
  suffix = c(".x", ".y"),
  keep = FALSE
)
```

## Chinook

```{r}
chinook_survey <- read_csv(here("data/chinook_salmon_survey.csv")) 

chinook_clean <- chinook_survey %>%
  clean_names() %>%
  mutate(haul_id = dataset_west_coast_triennial,
         stratum = x2,
         lat = x3,
         long = x4,
         depth = x5,
         year = x6,
         wtcpue = x7) %>%
  mutate(species = "chinook") %>%
  select(species, haul_id, stratum, lat, long, depth, year, wtcpue) %>%
  drop_na()
```

## Urchin

```{r}
urchin_survey <- read_csv(here("data/northern_heart_urchin_survey.csv")) 

urchin_clean <- urchin_survey %>%
  clean_names() %>%
  mutate(haul_id = dataset_west_coast_annual,
         stratum = x2,
         lat = x3,
         long = x4,
         depth = x5,
         year = x6,
         wtcpue = x7) %>%
  mutate(species = "urchin") %>%
  select(species, haul_id, stratum, lat, long, depth, year, wtcpue) %>%
  drop_na()
```

# Full join with urchin

```{r}
full_dung_squid_urch <- full_join(
  full_dung_squid,
  urchin_clean,
  by = NULL,
  suffix = c(".x", ".y"),
  keep = FALSE
) %>%
  filter(!wtcpue == 0)
```

# Full join with urchin

```{r}
full_dung_squid_chin <- full_join(
  full_dung_squid,
  chinook_clean,
  by = NULL,
  suffix = c(".x", ".y"),
  keep = FALSE
) %>%
  filter(!wtcpue == 0)
```

*West Coast Fisheries* Port complex git remote install How much has catch been affected by temperature: linear model

```{r}
# Run if you don't already have devtools installed
install.packages("devtools")

# Run once devtools is successfully installed
devtools::install_github("cfree14/wcfish", force=T)
library(wcfish)

all <- pacfin_all1

eis <- all %>%
  select(year, comm_name, value_usd, landings_mt, landings_kg, landings_lb, price_usd_lb) %>%
  filter(comm_name %in% c("Chinook salmon", "Dungeness crab", "Market squid", "Red sea urchin"))
```

```{r}
library(rerddap)
file_id <- rerddap::info(datasetid = "NOAA_DHW_monthly")

start = "2003-01-01"

end = "2022-12-31"

grid <- griddap(file_id,
                time = c(start, end),
                latitude = c(30, 49.2),
                longitude = c(-115, 130))$data
  
```
